// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/franklins/CommandCenterRefined.tsx": () => import("../components/mockups/franklins/CommandCenterRefined.tsx"),
  "./components/mockups/franklins/FranklinFinalDesktop.tsx": () => import("../components/mockups/franklins/FranklinFinalDesktop.tsx"),
  "./components/mockups/franklins/FranklinFinalMobile.tsx": () => import("../components/mockups/franklins/FranklinFinalMobile.tsx")
};
