import { useState } from "react";
import { AlertCircle, ArrowLeft, Bell, Check, CheckCircle2, ClipboardCheck, LayoutDashboard, Menu, Search, ShieldCheck, Truck, UsersRound } from "lucide-react";
import "./_final.css";

type MobileView = "login" | "queue" | "detail" | "recruiting";
const mobileDrivers = [["JC", "Jalen Carter", "Documents", "72%", "On track"], ["AM", "Avery Mitchell", "Background", "46%", "At risk"], ["RS", "Riley Santos", "Orientation", "91%", "Ready"]];

export function FranklinFinalMobile() {
  const [view, setView] = useState<MobileView>("login");
  const [menu, setMenu] = useState(false);
  return <main className="franklin-final ff-mobile">
    <div className="ff-preview-bar"><span className="ff-preview-label">MOBILE · 390px</span>{(["login", "queue", "detail", "recruiting"] as MobileView[]).map((item) => <button key={item} className={`ff-preview-tab ${view === item ? "active" : ""}`} onClick={() => setView(item)}>{item === "queue" ? "Queue" : item[0].toUpperCase() + item.slice(1)}</button>)}</div>
    {view === "login" ? <MobileLogin onSubmit={() => setView("queue")} /> : <div className="ff-mobile-app"><header className="ff-topbar"><button className="ff-icon-btn" aria-label="Open navigation" onClick={() => setMenu(!menu)}><Menu size={18} /></button><div className="ff-brand"><span className="ff-brand-mark">F</span>Franklins<span style={{ color: "#d0962e" }}>.</span>OS</div><button className="ff-icon-btn" aria-label="Notifications"><Bell size={17} /></button></header>{menu && <nav className="ff-mobile-menu"><button onClick={() => { setView("queue"); setMenu(false); }}><LayoutDashboard size={15} /> All Drivers</button><button onClick={() => { setView("recruiting"); setMenu(false); }}><UsersRound size={15} /> Recruiting</button><button onClick={() => { setView("detail"); setMenu(false); }}><ClipboardCheck size={15} /> Compliance</button></nav>}{view === "queue" && <MobileQueue onDetail={() => setView("detail")} />}{view === "detail" && <MobileDetail onBack={() => setView("queue")} />}{view === "recruiting" && <MobileRecruiting />}</div>}
  </main>;
}

function MobileLogin({ onSubmit }: { onSubmit: () => void }) {
  return <section className="ff-login"><div className="ff-login-form"><div className="ff-login-card"><div className="ff-brand"><span className="ff-brand-mark">F</span>Franklins<span style={{ color: "#d0962e" }}>.</span>OS</div><div className="ff-login-eyebrow">Driver operations platform</div><h1 className="ff-login-title">Move every driver forward.</h1><p className="ff-login-subtitle">Your clear workspace for recruiting, onboarding, and dispatch readiness.</p><form onSubmit={(event) => { event.preventDefault(); onSubmit(); }}><div className="ff-field"><label htmlFor="mobile-email">Work email</label><input id="mobile-email" className="ff-input" autoComplete="username" value="demo@franklins.local" readOnly /></div><div className="ff-field"><label htmlFor="mobile-password">Password</label><input id="mobile-password" className="ff-input" autoComplete="current-password" type="password" placeholder="Enter your password" /></div><button className="ff-btn ff-btn-primary ff-login-submit" type="submit">Sign in</button></form><p className="ff-help">DEV/DEMO · Synthetic data only</p></div></div><div className="ff-login-visual"><div className="ff-visual-content"><div className="ff-visual-kicker"><span /> Ready when you are</div><h2 className="ff-visual-title">A calmer way to run the next mile.</h2><p className="ff-visual-copy">Everything important, right where the work happens.</p></div></div></section>;
}

function MobileQueue({ onDetail }: { onDetail: () => void }) {
  return <div className="ff-mobile-page"><div className="ff-mobile-heading"><div><span className="ff-nav-label" style={{ margin: 0 }}>Franklin workspace</span><h1>All Drivers</h1><p>47 active · 18 ready</p></div><button className="ff-icon-btn"><Search size={17} /></button></div><div className="ff-metrics"><div className="ff-card ff-metric"><div className="ff-metric-top"><span>Ready</span><span className="ff-metric-icon"><CheckCircle2 size={15} /></span></div><div className="ff-metric-value">18</div><div className="ff-metric-foot ff-up">38% of active</div></div><div className="ff-card ff-metric"><div className="ff-metric-top"><span>Needs action</span><span className="ff-metric-icon warn"><AlertCircle size={15} /></span></div><div className="ff-metric-value">03</div><div className="ff-metric-foot ff-warn">2 due today</div></div></div><div className="ff-alert"><AlertCircle size={15} /><span>3 SLA risks need attention</span></div><div className="ff-mobile-section-head"><h2>Priority queue</h2><button className="ff-filter-chip">Filter</button></div><div className="ff-mobile-list">{mobileDrivers.map(([initials, name, stage, progress, status]) => <button className="ff-mobile-driver ff-card" key={name} onClick={onDetail}><span className="ff-avatar">{initials}</span><span className="ff-driver-name"><strong>{name}</strong><span>{stage} · {progress}</span></span><span className={`ff-status ${status === "At risk" ? "risk" : "ready"}`}>{status === "At risk" ? <AlertCircle size={12} /> : <CheckCircle2 size={12} />}{status}</span></button>)}</div><div className="ff-mobile-empty ff-card"><CheckCircle2 size={17} /><div><strong>All assigned</strong><span>No unassigned drivers in your queue.</span></div></div></div>;
}

function MobileDetail({ onBack }: { onBack: () => void }) {
  return <div className="ff-mobile-page"><button className="ff-back" onClick={onBack}><ArrowLeft size={14} /> All Drivers</button><div className="ff-card ff-mobile-detail-hero"><div className="ff-detail-person"><span className="ff-avatar">JC</span><div><h2>Jalen Carter</h2><p>Memphis, TN · Owner operator</p></div></div><span className="ff-status ready"><CheckCircle2 size={12} /> On track</span></div><div className="ff-card ff-mobile-detail-card"><h3 className="ff-section-title">Onboarding progress</h3><div className="ff-mobile-progress"><strong>4 of 6</strong><span>Documents</span><i><b /></i></div><div className="ff-detail-facts"><div className="ff-fact"><span>Owner</span><strong>Mason</strong></div><div className="ff-fact"><span>Phone</span><strong>•••• 4821</strong></div></div></div><div className="ff-card ff-action-card"><h3>Next best action</h3><p>Verify the medical card, then continue the Step 5 checklist.</p><button className="ff-btn ff-btn-primary">Open checklist</button></div><div className="ff-card ff-mobile-detail-card"><h3 className="ff-section-title">Recent activity</h3><p className="ff-mobile-activity"><Check size={14} /> Mason completed Drug Test <small>Today, 9:20 AM</small></p><p className="ff-mobile-activity"><ShieldCheck size={14} /> Clearing House result received <small>Yesterday</small></p></div></div>;
}

function MobileRecruiting() {
  return <div className="ff-mobile-page"><div className="ff-mobile-heading"><div><span className="ff-nav-label" style={{ margin: 0 }}>Franklin workspace</span><h1>Recruiting</h1><p>28 active leads · 4 in review</p></div><button className="ff-btn ff-btn-primary">New lead</button></div><div className="ff-mobile-stage"><span>New lead</span><strong>08</strong></div><div className="ff-mobile-stage"><span>Screening</span><strong>07</strong></div><div className="ff-mobile-stage active"><span>Manager review</span><strong>04</strong></div><div className="ff-card ff-mobile-case"><div className="ff-avatar">OP</div><div><strong>Owen Price</strong><span>Manager review · Due today</span></div><span className="ff-status risk"><AlertCircle size={12} /> Review</span></div></div>;
}

export default FranklinFinalMobile;